import './globals.css'
import { Nunito } from 'next/font/google'
import Navbar from './components/navbar/navbar';
import ClientOnly from './components/ClientOnly';
import Modal from './components/models/Modal';
import RegisterModal from './components/models/RegisterModal';
import ToasterProvider from './providers/ToasterProvider';
import LoginModal from './components/models/LoginModal';
import getCurrentUser from './actions/getCurrentUser';




export const metadata = {
  title: 'GRAB',
  description: 'Grab',
}

const font = Nunito({
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>

          <ToasterProvider/>
          <LoginModal/>
          <RegisterModal/>

          <Navbar currentUser = {currentUser}/>
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}

/*
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Nunito } from 'next/font/google'
import Navbar from './components/navbar/Navbar'

//const inter = Inter({ subsets: ['latin'] })
const inter = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'House Website ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        </body>
    </html>
  )
}
*/